language: python
python:
  - 2.7
sudo: false
install:
    - pip install tox --use-mirrors
script:
    - tox
notifications:
  irc:
    channels:
      - 'chat.freenode.net##stashbot'
    template:
       - "%{repository}#%{build_number} (%{branch} - %{commit} %{author}): %{message} - %{build_url}"
